# Prod Env is running in employee openshift
# with ACME Certs
# frontend used artifact image, because runtime image requires root
# privileges where are not avail on employee openshift:
specific:
  COMMON:
    DNS_BASENAME: "www.opendj.io"

#  BACKEND_EVENTSTORE:
#    KAFKA:
#      OPERATOR_AVAILABLE: false
#      TOPIC_CMD:  oc --namespace dfroehli-opendj-prd rsh backend-eventstore-zookeeper-0 /opt/kafka/bin/kafka-topics.sh --zookeeper localhost:21810 
 

  PROVIDER_SPOTIFY:
    LOG_LEVEL: "error"
    SPOTIFY_CALLBACK_URL: "http://www.opendj.io/api/provider-spotify/v1/auth_callback"
    REPLICAS: 2

  SERVICE_HOUSEKEEPING:
    LOG_LEVEL: "error"

  SERVICE_PLAYLIST:
    LOG_LEVEL: "error"
    TEST_EVENT_CREATE: "true"
    TEST_EVENT_ID: "demo"
    DEFAULT_AUTOFILL_EMPTY_PLAYLIST: "false"
    DEFAULT_IS_PLAYING: "true"
    MOCKUP_NO_ACTUAL_PLAYING: "false"
    MOCKUP_AUTOSKIP_SECONDS: "0"
    INTERNAL_POLL_INTERVAL: "5000"
    REPLICAS: 2

  SERVICE_WEB:
    LOG_LEVEL: "error"
    REPLICAS: 2

  SERVICE_EVENTACTIVITY:
    LOG_LEVEL: "ERROR"

  FRONTEND_WEB:
    REPLICAS: 1
    USE_ACME_CERTS: "true"
    SERVER_TIMEOUT: "10000"
  