- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    labels:
      app: service
      app.kubernetes.io/part-of: service
    name: service-eventactivity
    namespace: "{{ENV.COMMON.NAMESPACE|mandatory}}"
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      name: service-eventactivity
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 60
      resources: {}
      type: Rolling
    template:
      metadata:
        labels:
          name: service-eventactivity
          app: service
        name: service-eventactivity
        annotations:
#          app.openshift.io/connects-to: 'backend-eventstore-kafka'
      spec:
        containers:
          - env:
              - name: quarkus_log_console_level
                value: "{{ENV.SERVICE_EVENTACTIVITY.LOG_LEVEL | default('ALL')}}"
              - name: "mp_messaging_outgoing_event_activity_bootstrap_servers"
                value: "{{ENV.BACKEND_EVENTSTORE.KAFKA.HOST}}"
              - name: "quarkus.http.port"
                value: "8080"
            imagePullPolicy: {{ ENV.COMMON.CONTAINER.PULL_POLICY }}
            name: service-eventactivity-minimal
            resources:
              limits:
                cpu: 1000m
                memory: 128Mi
              requests:
                cpu: 0
                memory: 128Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
      - imageChangeParams:
          automatic: true
          containerNames:
            - service-eventactivity-minimal
          from:
            kind: ImageStreamTag
            name: 'service-eventactivity-minimal:{{ENV.COMMON.CONTAINER.IMAGE_TAG}}'
            namespace: "{{ENV.COMMON.CONTAINER_IMAGE_FROM_NAMESPACE | mandatory}}"
        type: ImageChange
      - type: ConfigChange

- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: service-eventactivity
    name: service-eventactivity
    namespace: "{{ENV.COMMON.NAMESPACE|mandatory}}"
  spec:
    ports:
      - name: web
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      name: service-eventactivity
    sessionAffinity: None
    type: ClusterIP
