# Prod Env is running in employee openshift
# with ACME Certs
# frontend used artifact image, because runtime image requires root
# privileges where are not avail on employee openshift:
specific:
  COMMON:
    NAMESPACE: "dfroehli-opendj-uat"
    DNS_BASENAME: "uat.opendj.io"
    GIT:
      REF: "master"
    CONTAINER_IMAGE_BUILD: false
    CONTAINER_IMAGE_TAG: "uat"
    CONTAINER_IMAGE_FROM_EXTERNAL_REGISTRY: true
    CONTAINER_IMAGE_REGISTRY: "quay.io/opendj"
    STORAGE_CLASS_FILE: "managed-nfs-storage"
  
  PROVIDER_SPOTIFY:
    LOG_LEVEL: "trace"
    SPOTIFY_CALLBACK_URL: "http://uat.opendj.io/api/provider-spotify/v1/auth_callback"
    REPLICAS: 1

  SERVICE_HOUSEKEEPING:
    LOG_LEVEL: "debug"

  SERVICE_PLAYLIST:
    LOG_LEVEL: "trace"
    TEST_EVENT_CREATE: "true"
    TEST_EVENT_ID: "demo"
    DEFAULT_AUTOFILL_EMPTY_PLAYLIST: "false"
    DEFAULT_IS_PLAYING: "true"
    MOCKUP_NO_ACTUAL_PLAYING: "false"
    MOCKUP_AUTOSKIP_SECONDS: "0"
    INTERNAL_POLL_INTERVAL: "5000"
    REPLICAS: 1

  SERVICE_WEB:
    LOG_LEVEL: "debug"
    REPLICAS: 1

  SERVICE_EVENTACTIVITY:
    LOG_LEVEL: "ERROR"

  FRONTEND_WEB:
    REPLICAS: 1
    USE_ACME_CERTS: "true"
    SERVER_TIMEOUT: "10000"
  