# Variables specific for DEV stage:

# These cert are valid for dev.opendj.io
# created using lets encrypt openshift-acme in demo env
# PROBLEM: let's encrypt does not work for dev env, as it is not
# in public internet. So we use a tricky hack:
# Step 1: Change dns entry dev.opendj.io from stormshift to demo env
# Step 2: create a dummy route in demo env there with hostname dev.opendj.io
# Step 3: Openshift acme will create a cert and add it to the dummy route
# Step 4: Export cert and key from there to here:
# Step 5: change back dns entry to stormshift

specific:
      COMMON:
            CONTAINER_IMAGE_TAG: "master"
            K8S_KUBECONFIG: "/Users/dfroehli/RedHat/projects/OpenDJ/secret_dev_kubeconfig.yml"

#      BACKEND_EVENTSTORE:
#            KAFKA:
#                  NUM_BROKERS: 2
#                  NUM_ZOOKEPERS: 1

      BACKEND_DATAGRID:
            REPLICAS: 1

      PROVIDER_SPOTIFY:
            LOG_LEVEL: "trace"
            REPLICAS: 2

      SERVICE_PLAYLIST:
            LOG_LEVEL: "trace"
            TEST_EVENT_ID: "demo"
            DEFAULT_AUTOFILL_EMPTY_PLAYLIST: "true"
            MOCKUP_NO_ACTUAL_PLAYING: "true"
            MOCKUP_AUTOSKIP_SECONDS: "20"
            INTERNAL_POLL_INTERVAL: "20000"
            REPLICAS: 2

      SERVICE_WEB:
            REPLICAS: 2

      FRONTEND_WEB:
            REPLICAS: 2
            USE_ACME_CERTS: false
            TLS_CERT: |
                  -----BEGIN CERTIFICATE-----
                  MIIGUjCCBTqgAwIBAgISAzmCQKWQ+SEoC9xloRxd+obPMA0GCSqGSIb3DQEBCwUA
                  MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
                  ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xOTA3MDcxMTE5MjJaFw0x
                  OTEwMDUxMTE5MjJaMBgxFjAUBgNVBAMTDWRldi5vcGVuZGouaW8wggIiMA0GCSqG
                  SIb3DQEBAQUAA4ICDwAwggIKAoICAQC/UAAiGhXazN4a3KfhWg1KGHt7MGAbyvuT
                  XK1xCuoPrllidE4+LkjjLyyRyFvJtXVc/0xAJwUNrxN2uLZm/GBrcBGP6LtcJX8D
                  /lH8evGHAqeAPuDKG6THeyJF+QwpSO9TSZpNc0Xs+lTGf9tlqWkIQZujdJyXkFCt
                  kfg9vk4vBz5x95nQvUcTiaL2mgWBlQ3k+6svnC4HBDsHiFtgIstd7iMGfQNBcAf7
                  ook0S4AXJjVWIdZ9lnKfVhasfbgsxr9tBBb3Ybo+7EQ+9Fitn+D5y8nYFT4T5UC9
                  ISjoq1edL5O/f8XF5sGMsvL8gd2no600Ll5cSUpAjdcpAJseqzCLipL7b1s/Uei0
                  E+ZouEjEZyCmkQ/QY9jYmGiGWj7ysNyCPwkoKROm8qOPjy7RCZ+vVqHvVHGk8UJc
                  HI41znWgscS/8ULXQeILPw6ZKgYWRfg2aIuBy+Jo1E2/uyTYtY5gXu5tj6fC4Hgz
                  82vT5EuUrBRWtQt2hJhSrurQC/JeqYVqQokJsNFeeCXaT5kIz4R67AFrNPZlEsgd
                  D/HUtX0Fx+KIPBRpUXjNLtnxRRVl58FT6CegkVZfjw9QUA+zSsRV+3sNlIJw+5ub
                  Oy4ilUSs7xDWJHu0Cthsk0Ew8nOPfoMuX/tYY4l4sQrEmh+MNjrGhIx85tkvbxMJ
                  5XvA2tUc5wIDAQABo4ICYjCCAl4wDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQG
                  CCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBTUkY2k
                  HfQ1/NtZg9D2QUb152yNOzAfBgNVHSMEGDAWgBSoSmpjBH3duubRObemRWXv86js
                  oTBvBggrBgEFBQcBAQRjMGEwLgYIKwYBBQUHMAGGImh0dHA6Ly9vY3NwLmludC14
                  My5sZXRzZW5jcnlwdC5vcmcwLwYIKwYBBQUHMAKGI2h0dHA6Ly9jZXJ0LmludC14
                  My5sZXRzZW5jcnlwdC5vcmcvMBgGA1UdEQQRMA+CDWRldi5vcGVuZGouaW8wTAYD
                  VR0gBEUwQzAIBgZngQwBAgEwNwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYa
                  aHR0cDovL2Nwcy5sZXRzZW5jcnlwdC5vcmcwggEEBgorBgEEAdZ5AgQCBIH1BIHy
                  APAAdQBvU3asMfAxGdiZAKRRFf93FRwR2QLBACkGjbIImjfZEwAAAWvMX9v9AAAE
                  AwBGMEQCIHdsblCKJXA1ORtpvqvfsjJBRjFmDbmiOkI6zlBkb2l7AiA5H3gfcnHq
                  pRNO1NwaxIP6vSmhtzJr4E+WBh1kI2M/lwB3AGPy283oO8wszwtyhCdXazOkjWF3
                  j711pjixx2hUS9iNAAABa8xf28gAAAQDAEgwRgIhAJxdsQ/CdASwCVJXNrIXFAac
                  N0ut1E3aDt8oOpxMw2V0AiEA+6etK0RmA3xVLdgGmSSowBM2HhUP/9Qz3Mq1Ej83
                  mXQwDQYJKoZIhvcNAQELBQADggEBAGwBoMw/tZr6PW23Ckvj4GPO7zj4Wf1MTnKC
                  1fq35PWltPpkmyvdQS+pk6C/6Vjqtf+H+8S2uwzN1X6YqQBxQD1iLTFLsfSEWHgz
                  c+kaNRErObP0yNzjIb1dvQkeYUPG/ktIMTMIkdWDnA+2gcMVeu0KTMPjs/lv/MjA
                  w77OO22C1MSBLLb2d5C0u9SBZ5WELl/iA+4lxzueR7BTAbV2kGl2qif6qPr6y6wo
                  euZp2R9pc/0v9lU9QrWnFYzEKIuqsK6eVK8Vcr1aC4UxekRmSPFMGDGKvysVSeZj
                  8G3r/dgQ1z45lgSYx5Q2M8SFopC0n6vRq8orG37JhwaSTiv9lLw=
                  -----END CERTIFICATE-----
                  -----BEGIN CERTIFICATE-----
                  MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/
                  MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
                  DkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0Nlow
                  SjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMT
                  GkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOC
                  AQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EF
                  q6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8
                  SMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0
                  Z8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWA
                  a6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj
                  /PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0T
                  AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIG
                  CCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNv
                  bTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9k
                  c3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAw
                  VAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcC
                  ARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAz
                  MDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwu
                  Y3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsF
                  AAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJo
                  uM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/
                  wApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwu
                  X4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlG
                  PfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6
                  KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==
                  -----END CERTIFICATE-----
            TLS_KEY: "{{ VAULT_TLS_KEY_DEV_OPENDJ_IO}}"
